name: CI

on:
  push:
    branches: [ main ]
  pull_request:

defaults:
  run:
    working-directory: app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: app/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: pnpm run format && git diff --exit-code
      - run: pnpm run lint
      - run: pnpm run typecheck
      - run: pnpm run test
      - run: pnpm run test:e2e
      - run: pnpm run build
      - name: Build Docker image
        run: docker build -t gcr.io/my-project/cyo-curriculum:$(git rev-parse --short HEAD) .
      - name: Push image
        run: echo "TODO: configure GCR auth"
